# Generated by Django 5.1.4 on 2024-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0007_student_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursefullname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseshortname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
