# Generated by Django 5.1.4 on 2024-12-08 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0008_course_course_id_alter_course_coursefullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='coursefullname',
            field=models.CharField(default='True', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseshortname',
            field=models.CharField(default='True', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
